// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: proto/service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AttackForgeService_GetMetrics_FullMethodName  = "/pb.AttackForgeService/GetMetrics"
	AttackForgeService_GetTools_FullMethodName    = "/pb.AttackForgeService/GetTools"
	AttackForgeService_ControlTool_FullMethodName = "/pb.AttackForgeService/ControlTool"
	AttackForgeService_StreamState_FullMethodName = "/pb.AttackForgeService/StreamState"
)

// AttackForgeServiceClient is the client API for AttackForgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttackForgeServiceClient interface {
	GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
	GetTools(ctx context.Context, in *ToolsRequest, opts ...grpc.CallOption) (*ToolsResponse, error)
	ControlTool(ctx context.Context, in *ControlToolRequest, opts ...grpc.CallOption) (*ControlToolResponse, error)
	StreamState(ctx context.Context, in *StreamStateRequest, opts ...grpc.CallOption) (AttackForgeService_StreamStateClient, error)
}

type attackForgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttackForgeServiceClient(cc grpc.ClientConnInterface) AttackForgeServiceClient {
	return &attackForgeServiceClient{cc}
}

func (c *attackForgeServiceClient) GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, AttackForgeService_GetMetrics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attackForgeServiceClient) GetTools(ctx context.Context, in *ToolsRequest, opts ...grpc.CallOption) (*ToolsResponse, error) {
	out := new(ToolsResponse)
	err := c.cc.Invoke(ctx, AttackForgeService_GetTools_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attackForgeServiceClient) ControlTool(ctx context.Context, in *ControlToolRequest, opts ...grpc.CallOption) (*ControlToolResponse, error) {
	out := new(ControlToolResponse)
	err := c.cc.Invoke(ctx, AttackForgeService_ControlTool_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attackForgeServiceClient) StreamState(ctx context.Context, in *StreamStateRequest, opts ...grpc.CallOption) (AttackForgeService_StreamStateClient, error) {
	stream, err := c.cc.NewStream(ctx, &AttackForgeService_ServiceDesc.Streams[0], AttackForgeService_StreamState_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &attackForgeServiceStreamStateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AttackForgeService_StreamStateClient interface {
	Recv() (*StreamStateResponse, error)
	grpc.ClientStream
}

type attackForgeServiceStreamStateClient struct {
	grpc.ClientStream
}

func (x *attackForgeServiceStreamStateClient) Recv() (*StreamStateResponse, error) {
	m := new(StreamStateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AttackForgeServiceServer is the server API for AttackForgeService service.
// All implementations must embed UnimplementedAttackForgeServiceServer
// for forward compatibility
type AttackForgeServiceServer interface {
	GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error)
	GetTools(context.Context, *ToolsRequest) (*ToolsResponse, error)
	ControlTool(context.Context, *ControlToolRequest) (*ControlToolResponse, error)
	StreamState(*StreamStateRequest, AttackForgeService_StreamStateServer) error
	mustEmbedUnimplementedAttackForgeServiceServer()
}

// UnimplementedAttackForgeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAttackForgeServiceServer struct {
}

func (UnimplementedAttackForgeServiceServer) GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedAttackForgeServiceServer) GetTools(context.Context, *ToolsRequest) (*ToolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTools not implemented")
}
func (UnimplementedAttackForgeServiceServer) ControlTool(context.Context, *ControlToolRequest) (*ControlToolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ControlTool not implemented")
}
func (UnimplementedAttackForgeServiceServer) StreamState(*StreamStateRequest, AttackForgeService_StreamStateServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamState not implemented")
}
func (UnimplementedAttackForgeServiceServer) mustEmbedUnimplementedAttackForgeServiceServer() {}

// UnsafeAttackForgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttackForgeServiceServer will
// result in compilation errors.
type UnsafeAttackForgeServiceServer interface {
	mustEmbedUnimplementedAttackForgeServiceServer()
}

func RegisterAttackForgeServiceServer(s grpc.ServiceRegistrar, srv AttackForgeServiceServer) {
	s.RegisterService(&AttackForgeService_ServiceDesc, srv)
}

func _AttackForgeService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttackForgeServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttackForgeService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttackForgeServiceServer).GetMetrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttackForgeService_GetTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttackForgeServiceServer).GetTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttackForgeService_GetTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttackForgeServiceServer).GetTools(ctx, req.(*ToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttackForgeService_ControlTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttackForgeServiceServer).ControlTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttackForgeService_ControlTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttackForgeServiceServer).ControlTool(ctx, req.(*ControlToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttackForgeService_StreamState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AttackForgeServiceServer).StreamState(m, &attackForgeServiceStreamStateServer{stream})
}

type AttackForgeService_StreamStateServer interface {
	Send(*StreamStateResponse) error
	grpc.ServerStream
}

type attackForgeServiceStreamStateServer struct {
	grpc.ServerStream
}

func (x *attackForgeServiceStreamStateServer) Send(m *StreamStateResponse) error {
	return x.ServerStream.SendMsg(m)
}

// AttackForgeService_ServiceDesc is the grpc.ServiceDesc for AttackForgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttackForgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AttackForgeService",
	HandlerType: (*AttackForgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetrics",
			Handler:    _AttackForgeService_GetMetrics_Handler,
		},
		{
			MethodName: "GetTools",
			Handler:    _AttackForgeService_GetTools_Handler,
		},
		{
			MethodName: "ControlTool",
			Handler:    _AttackForgeService_ControlTool_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamState",
			Handler:       _AttackForgeService_StreamState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/service.proto",
}
