; ==============================================================================
; PHP Overrides to introduce vulnerabilities (Lab environment only)
; ==============================================================================

; Enable file uploads
file_uploads = On

; Enable opening remote URLs (LFI/RFI vulnerability support)
allow_url_fopen = On
allow_url_include = On

; Display errors to help users exploit SQLi / Debug applications
display_errors = On
display_startup_errors = On
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

; Load the file to disable strict mysqli reports (required for old PHP apps)
auto_prepend_file = /usr/local/etc/php/disable_strict_mysqli.php
