# ==============================================================================
# HACKTHACKER LABS - SECURITY SHEPHERD DATABASE CONFIGURATION
# ==============================================================================
FROM alpine:3.24 AS cloner
RUN apk add --no-cache git
WORKDIR /src
RUN git clone --depth 1 https://github.com/OWASP/SecurityShepherd.git .

FROM mariadb:11.4
COPY --from=cloner /src/src/main/resources/database/coreSchema.sql /docker-entrypoint-initdb.d/coreSchema.sql
COPY --from=cloner /src/src/main/resources/database/moduleSchemas.sql /docker-entrypoint-initdb.d/moduleSchemas.sql

USER root
RUN sed -i 's/@'\''localhost'\''/@'\'''%''\''/g' /docker-entrypoint-initdb.d/moduleSchemas.sql && \
    sed -i 's/-- DELIMITER/DELIMITER/g' /docker-entrypoint-initdb.d/*.sql && \
    sed -i 's/-- \$\$/\$\$/g' /docker-entrypoint-initdb.d/*.sql

USER mysql
