# ==============================================================================
# HACKTHACKER LABS - OWASP WRONGSECRETS DOCKER CONFIGURATION
# ==============================================================================
FROM jeroenwillemsen/wrongsecrets:latest-no-vault
